### ISSUE TITLE
emacs files should not go into user directory

### ISSUE THREAD

**Issue by jvillasante** [SystemCrafters/crafted-emacs#163]
While `rational-config-var-directory` is a nice touch, I would rather have all Emacs related files (history, etc.) inside `user-emacs-directory`, right now that's cluttering my personal config.

**Comment by jeffbowman** [comment]
Thanks for the issue! I believe #158 might be the PR you are looking for. When it is finished I'll merge it and that should help out. If that PR does not handle a specific file you are seeing, mention it here and we'll do what we can to assist.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs V2
