### ISSUE TITLE
A proper naming convention for modules

### ISSUE THREAD

**Issue by binarydigitz01** [SystemCrafters/crafted-emacs#169]
Also said by System Crafters in his stream, the modules need a better naming convention. I would like to propose an organisation system similar to doom's, where certain modules are organized within folders. For e.g., all language modules can be together in modules/languages, and so on.

**Comment by telenieko** [comment]
> Also said by System Crafters in his stream

For completeness/context, could you link the stream here? And if possible add a timestamp as the stream is probably 1-2 hour long.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs V2
