### ISSUE TITLE
native-compile-async: Native compiler error

### ISSUE THREAD

**Issue by ghost** [SystemCrafters/crafted-emacs#181]
Fresh install I get
native-compile-async: Native compiler error: "Path not a file nor directory", "/home/perrierjouet/.config/rational-emacs/early-config.el"

in my .zshrc I have RATIONAL_EMACS_HOME=~/.config/rational-emacs

**Comment by alternateved** [comment]
Hello!

As stated in README [here](https://github.com/SystemCrafters/rational-emacs/tree/475d7a4dec7f589098181e23b18fa28186602538#how-the-rational-config-file-is-found), you would need to create `early-config.el` file yourself in your `$RATIONAL_EMACS_HOME`.

Please refer to this paragraph:
> Once the rational-config-path is determined, if it does not exist in the filesystem, it is created. However, just the path is created, the files config.el and early-config.el must be created by you.

**Comment by ajxn** [comment]
This should not stop rational-emacs from loading.  The early-config.el should only be loaded if it exists.
I have not looked into the code so I don't know if this is an error or just an informative message.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs V2, and Emacs 29+ probably solves this problem out-of-the-box.
