### ISSUE TITLE
rational-windows-evil-style in rational-windows.el

### ISSUE THREAD

**Issue by vaidyafamily** [SystemCrafters/crafted-emacs#186]
There is a variable in rational-windows.el, rational-windows-evil-style, that doesn't seem to be used anywhere. Was the intention to only have the windows keybindings set if the variable was nil, or was it something else? Do we want to implement that, or should we get rid of the variable?

**Comment by jeffbowman** [comment]
Maybe @daviwil can speak to this? I'm not a `evil` user myself, so I'm not sure how to best answer this question.

**Comment by jvdydev** [comment]
A fellow `evil` user here, my assumption would be that it was intended to be used as a guard to not enable `winner-mode` so the `evil` frame/window management keybindings can take over.

They don't overlap by default (`evil` maps to `C-w`, crafted maps to `C-c w`), so it's not a direct conflict (although we may want to remove the variable and disable winner-mode when evil is loaded?).

**Comment by jeffbowman** [comment]
Any further discussion on this?  Do we still need to consider this in the context of the `crafted-evil-config` module? 

cc: @jvdydev

**Comment by jvdydev** [comment]
I think this can be closed, any notion of that variable has been removed at some point for v2 (the `-windows` module was completely removed and the things moved into `crafted-defaults` are unrelated).

I don't think there is much benefit to having an evil style for `winner-mode` as `evil-mode` already implements evil-style window switching.
Worst case, we can re-open it or make a new issue for it in the context of crafted-v2.
