### ISSUE TITLE
Rename to Crafted Emacs

### ISSUE THREAD

**Issue by daviwil** [SystemCrafters/crafted-emacs#187]
I think this is the best-sounding formulation of a name (thanks @jeffbowman!) that fulfills two goals:

- Doesn't sound vaguely elitist
- Fits better with the "brand" of the System Crafters community

To affect the change, I think we should create a new branch where we do all of the module renaming and documentation updates before we flip the switch and rename the entire repo (it should also be `crafted-emacs` once this is done).

I've created a branch called `crafted-rename` to start this work but anyone can send PRs to help!

**Comment by daviwil** [comment]
See also the sibling repo I just created: https://github.com/SystemCrafters/crafted-guix

**Comment by jeffbowman** [comment]
PR #194 submitted for this. Needs review to make sure I didn't goof anything up.
