### ISSUE TITLE
How do you feel about a few new keybindings in rational-windows.el

### ISSUE THREAD

**Issue by vaidyafamily** [SystemCrafters/crafted-emacs#188]
The rational-windows module enables winner-mode and provides a keybinding to `winner-undo`. For symmetry, should we add `C-c w r` as a keybinding to `winner-redo`?

Additionally, I wonder if it makes sense to add a keybinding for `delete-window`?

**Comment by jeffbowman** [comment]
Good questions, but really, if you think they would be helpful to the community feel free to submit a PR. :-)

**Comment by vaidyafamily** [comment]
@jeffbowman Thanks for the advice. I didn't know the etiquette here. I thought that an issue for discussion was proper prior to submitting a PR. In the future I will submit a PR directly.

**Comment by jeffbowman** [comment]
Its not wrong to open an issue for discussion, we just don't get quite the same level of interaction, so you'll be waiting for a while before submitting the PR. If you open an issue (like a bug or feature request) then make sure you tag the issue in your commit on the PR (if you make one) that way the two get linked. Words like "Closes #188" or "Fixes #188"  for example will cause this issue to close when the PR is merged.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs v2, which also provides this keybinding thus resolving this issue.
