### ISSUE TITLE
early-init load-theme interferes with modus-operandi theme minibuffer prompt face

### ISSUE THREAD

**Issue by Cerebus** [SystemCrafters/crafted-emacs#193]
The deeper-blue theme loaded in early-init sets the minibuffer prompt face that seems to get stuck.  When modus-operandi loads, all prompt faces /except/ minibuffer-prompt get set to the theme.

Because deeper-blue uses a cyan foreground, the minibuffer prompt becomes unreadable modus-operandi's light backgrounds.

The easy fix is to remove this early load-theme.  Since I use a light theme I don't notice any UI flash.  :)   When removed, modus-operandi sets the minibuffer prompt face properly.

I'm not sure if this is really a rational-emacs issue or not, but out of the multiple emacs distros I play with, this is the only one where the prompt face gets stuck like this.

https://github.com/SystemCrafters/rational-emacs/blob/83f217884d25e30ac23403b136ef0539c8f9395e/early-init.el#L88

**Comment by jeffbowman** [comment]
You need to disable the theme when you switch it.  Try this code:

```emacs-lisp
(progn
  (disable-theme 'deeper-blue)
  (load-theme 'modus-operandi t))
```

**Comment by ajxn** [comment]
Maybe something that need to be documented?
