### ISSUE TITLE
Default local directory for `elpa`

### ISSUE THREAD

**Issue by abarocio80** [SystemCrafters/crafted-emacs#204]
I noticed that by default `crafted-package-bootstrap` (#201) puts its `elpa` directory unde `use-emacs-directory`. Is this the expected behaviour?

If so, wouldn't it be better to put all package directories (no matter what system is being using) in another directory? Could it be under `crafted-config-path`, like it is with `'straight`? Or could it be under something like `~/.local/share/crafted-emacs/`?

**Comment by jeffbowman** [comment]
The default location for `package-user-dir` is the `elpa` folder in the `user-emacs-directory` location.  I can move it to `crafted-config-path`, that's probably a good idea for consistency purposes, I just didn't do that as I didn't think of it before.  Thanks for the idea!!
