### ISSUE TITLE
Installing packages from source

### ISSUE THREAD

**Issue by oatmealm** [SystemCrafters/crafted-emacs#211]
Hi. What's the recommended way to install packages from source at the moment?

**Comment by ajxn** [comment]
From where?  From your `config.el` or `early-config.el` or from a module in `module`or `custom-module`?

If your use your config files, then use the package system that you know which you have choosen (`package` by default or `straight` if you choose to use). You can also use the two macros from `bootstrap/crafted-package.el`.

If you load from a module, then use the macros from `bootstrap/crafted-package.el` (`crafted-package-install-package` or `crafted-package-installed-p`).

At least as I understand it.

**Comment by oatmealm** [comment]
@ajxn i should have looked at the bootstrap code. Thank you!

**Comment by ajxn** [comment]
No problem.  Can this issue be closed?  If so, please close it as it still can be reopen if there is some thing to be added.

**Comment by oatmealm** [comment]
Hi, I looked again, I don't see any macro designed frop pulling source... I guess I'll have to use `straight` or similiar...?

**Comment by jeffbowman** [comment]
If you want to pull packages directly from GitHub or similar, you have all the normal options (el-get, straight, quelpa, borg, etc).  Using only MELPA as a package source will be similar in the sense the package was built directly from the latest commit in version control.  If you expect to need or want to modify the package after it is installed, any of the options will work, but if you then wish to push changes back to the package author, you may prefer something other than `package.el` for your package management. As for what is currently integrated in crafted-emacs, only `straight` of the options already mentioned is available.

**Comment by meleein1** [comment]
Use early-config.el to use straight.el

in config.org
* Tangling to early-config.el
If you need to make settings to =early-config.el=, you can do that from here, too.
Just begin the source code block with:
#+begin_src emacs-lisp :tangle ./early-config.el
(setq package-enable-at-startup nil)
(setq crafted-package-system 'straight)
(crafted-package-bootstrap crafted-package-system)
;; use straight.el with use-pakcage
(straight-use-package 'use-package)
#+end_src

**Comment by bboytian** [comment]
I've realised that when using chemacs2, you do not want to turn on `striaght-p` within the `.emacs-profile.el`, as that would be double bootstrapping. And the chemacs2 straight boothstrapping doesnt seem to be compatible with crafted-emacs.

**Comment by jeffbowman** [comment]
Closing as the final comment seems to provide the necessary solution
