### ISSUE TITLE
Symbol's value as variable is void: ns-function-modifier

### ISSUE THREAD

**Issue by cwulfman** [SystemCrafters/crafted-emacs#214]
After updating my copy of the repo, I get this error at startup:

> Symbol's value as variable is void: ns-function-modifier

The module `crafted-osx.el` should check to see which version of emacs is being run:
https://github.com/SystemCrafters/crafted-emacs/blob/380d66fefe37a5b388e7205312591c9bf33d3ca2/modules/crafted-osx.el#L40

```lisp
(when (featurep 'ns)
  (customize-set-variable ns-function-modifier 'hyper))
```

I'm running on a Mac, using the "Mac Port" version of emacs (see https://github.com/railwaycat/homebrew-emacsmacport)

**Comment by jeffbowman** [comment]
Thanks for the report!

**Comment by cwulfman** [comment]
Thanks for the work you-all are doing on crafted emacs!
