### ISSUE TITLE
use /modules/crafted-python.el on straight.el error

### ISSUE THREAD

**Issue by meleein1** [SystemCrafters/crafted-emacs#218]
hi there.

in /modules/crafted-python.el
;;; anaconda
	;; move anaconda python installation directory to
	;; `crafted-config-var-directory'
	(customize-set-variable
	 'anaconda-mode-installation-directory
	 (expand-file-name "anaconda-mode" crafted-config-var-directory))
	
	;; for those who use posframe, use it to show docs
	(when (and (**package-installed-p** 'posframe)
	           (featurep 'posframe))
	  (customize-set-variable 'anaconda-mode-use-posframe-show-doc t))

change
;;; anaconda
	;; move anaconda python installation directory to
	;; `crafted-config-var-directory'
	(customize-set-variable
	 'anaconda-mode-installation-directory
	 (expand-file-name "anaconda-mode" crafted-config-var-directory))
	
	;; for those who use posframe, use it to show docs
	(when (and (**crafted-package-installed-p** 'posframe)
	           (featurep 'posframe))
	  (customize-set-variable 'anaconda-mode-use-posframe-show-doc t))

after change OK.

**Comment by jeffbowman** [comment]
Thanks! Nice catch!
