### ISSUE TITLE
Issue with package install/loading in config.el when using crafted-emacs and chemacs2

### ISSUE THREAD

**Issue by ajeshp** [SystemCrafters/crafted-emacs#220]
I have done the following:
`chemacs2` is cloned to `~/.emacs.d`
`crafted-emacs` is cloned to `~/.config/emacs`
`~/.emacs-profiles.el` is set as follows:
```
(("default" . ((user-emacs-directory . "~/.emacs.default")))
 ("crafted" . ((user-emacs-directory . "~/.config/emacs"))))
 ```
When starting emacs with using the `crafted` profile, all `crafted-emacs` default packages, for eg: `marginalia`, `embark`, `vertico` are installed in `~/.config/emacs/elpa/` directory and any packages specified in my `crafted-config-file` (which is set to `~/.config/emacs/crafted-emacs`) are installed in `~/.config/emacs/crafted-emacs/elpa/`.
This causes issues when emacs is relaunched as it tries to install the packages specified in `crafted-config-file` again on every relaunch

I am working around this issue by creating a symlink: `~/.config/emacs/crafted-emacs/elpa -> ../elpa`

Note that this issue exists only when using `chemacs2`.
That is, without `chemacs2`, If I clone `crafted-emacs` to `~/.config/emacs`, then the `elpa` directory is created in `~/.config/crafted-emacs/elpa` and the `config.el` will also in the same directory, so there is no issue
Wondering if this should also be the case when using chemacs2

**Comment by jeffbowman** [comment]
Thanks for the thorough and complete description, I'm looking into it!

**Comment by jeffbowman** [comment]
The issue is `chemacs` moves the `package-user-dir` to the profile's `user-emacs-directory` and then loads the profile's `init.el`.  Bootstrapping `package.el` in `early-init.el` also sets the `package-user-dir`, so `chemacs` is clobbering that configuration.  I have a PR to resolve the issue, but documenting it here as well.
