### ISSUE TITLE
Get started guide for managing the configuration as git submodule

### ISSUE THREAD

**Issue by haroon-sheikh** [SystemCrafters/crafted-emacs#222]
I currently have version controlled my configuration including the .emacs.d directory in a dotfiles repo as I'm sure a lot of others do too.  

I think it would be a good idea to document a way for adding crafted-emacs repo as a git submodule so that it's easier to manage and keep it up-to-date. 

Would you be able to provide some guidance on how we could achieve a following folder structure?

```sh
.emacs.d/
.emacs.d/crafted-emacs/config.el
.emacs.d/crafted-emacs/crafted-emacs (as git submodule)
```

**Comment by jeffbowman** [comment]
Probably out of scope for this project to be providing a tutorial on git usage, but what you are suggesting can be addressed by following the guidance from here: [Git Submodules Doc](https://git-scm.com/book/en/v2/Git-Tools-Submodules), and you can add an environment variable to point to your crafted configuration, in this case you might set the following environment variable for your OS:

Most unixes
`CRAFTED_EMACS_HOME=$HOME/.emacs.d/crafted-emacs`
Microsoft Windows (maybe?)
`CRAFTED_EMACS_HOME=%USERPROFILE%\AppData\Roaming\.emacs.d\crafted-emacs`

This is an interesting idea though, would you be willing to put together a PR to update the README.org file and the documentation found in the `docs` folder? (See the `docs/CONTRIBUTING.org` file for how to go about it).

Thanks!

**Comment by ajxn** [comment]
Could it be some way that it  could be combined with  #224 ?

**Comment by jeffbowman** [comment]
Those are separate concerns. One is the xdg path, this is about having a `.config/emacs` directory already under version control and then wanting to use something like `git submodule add https://github.com/SystemCrafters/crafted-emacs` to have a version controlled `crafted-emacs` folder within from which modules might be loaded.  Using the xdg stuff would most likely break this a bit as things would be scattered all over the `.local`, `.cache`, and `.config` directories, so using a submodule in that scenario might be suboptimal. 

Just my $0.02.

**Comment by haroon-sheikh** [comment]
Hi @jeffbowman, Ive just managed to watch the v2 stream. Really enjoyed it  👏 and it should also resolve this. Any ideas on timeline around when this is likely to make it main branch.

**Comment by jeffbowman** [comment]
@haroon-sheikh We are very close to releasing RC1 of Crafted Emacs V2, which means V2 is right around the corner.  You might check my blog where I post updates on this progress and plans moving forward: (https://write.as/jeffbowman/). 

I'm closing this ticket now in anticipation of the Crafted Emacs V2 release.  Thanks for your interest, stay tuned, I'll be putting out as much communication on the actual release when it happens, hopefully in few weeks or less.
