### ISSUE TITLE
emacs on daemon. warning init.el

### ISSUE THREAD

**Issue by meleein1** [SystemCrafters/crafted-emacs#228]
When emacs on daemon.

have warnings.

Warning (initialization): An error occurred while loading ‘/home/meleeis/.config/emacs/init.el’:

Wrong type argument: wholenump, -8

Debugger entered--Lisp error: (wrong-type-argument wholenump -8)
  make-string(-8 32)
  (concat (make-string (- (/ (window-width) 2) welcome-mid) 32) welcome-text)
  (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len (length welcome-text)) (welcome-mid (/ welcome-len 2))) (concat (make-string (- (/ (window-width) 2) welcome-mid) 32) welcome-text))
  (cons (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len (length welcome-text)) (welcome-mid (/ welcome-len 2))) (concat (make-string (- (/ (window-width) 2) welcome-mid) 32) welcome-text)) (cons ':face (cons 'variable-pitch (cons ':link (cons (list "View Crafted Emacs Manual" #'(lambda ... ...)) '("\11View the Crafted Emacs manual using Info\n" "\n"))))))
  (cons '(variable-pitch font-lock-comment-face (:height 1.5) bold) (cons (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len (length welcome-text)) (welcome-mid (/ welcome-len 2))) (concat (make-string (- (/ (window-width) 2) welcome-mid) 32) welcome-text)) (cons ':face (cons 'variable-pitch (cons ':link (cons (list "View Crafted Emacs Manual" #'...) '("\11View the Crafted Emacs manual using Info\n" "\n")))))))
  (cons ':face (cons '(variable-pitch font-lock-comment-face (:height 1.5) bold) (cons (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len (length welcome-text)) (welcome-mid (/ welcome-len 2))) (concat (make-string (- (/ ... 2) welcome-mid) 32) welcome-text)) (cons ':face (cons 'variable-pitch (cons ':link (cons (list "View Crafted Emacs Manual" ...) '...)))))))
  (list (cons ':face (cons '(variable-pitch font-lock-comment-face (:height 1.5) bold) (cons (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len (length welcome-text)) (welcome-mid (/ welcome-len 2))) (concat (make-string (- ... welcome-mid) 32) welcome-text)) (cons ':face (cons 'variable-pitch (cons ':link (cons ... ...))))))))
  (defconst crafted-startup-text (list (cons ':face (cons '(variable-pitch font-lock-comment-face (:height 1.5) bold) (cons (let* ((welcome-text "Welcome to Crafted Emacs!\n\n") (welcome-len ...) (welcome-mid ...)) (concat (make-string ... 32) welcome-text)) (cons ':face (cons 'variable-pitch (cons ... ...))))))) "A list of texts to show in the middle part of spla...")
  eval-buffer(#<buffer  *load*-124135> nil "/home/meleeis/.config/emacs/modules/crafted-startu..." nil t)  ; Reading at buffer position 1804
  load-with-code-conversion("/home/meleeis/.config/emacs/modules/crafted-startu..." "/home/meleeis/.config/emacs/modules/crafted-startu..." nil t)
  require(crafted-startup)
  eval-buffer(#<buffer  *load*> nil "/home/meleeis/.config/emacs/init.el" nil t)  ; Reading at buffer position 4875
  load-with-code-conversion("/home/meleeis/.config/emacs/init.el" "/home/meleeis/.config/emacs/init.el" t t)
  load("/home/meleeis/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1590e6a0b80d>) #f(compiled-function () #<bytecode 0x1590e6a0b825>) t)
  command-line()
  normal-top-level()

I don't know the details. I think "(require 'crafted-startup)" have problem.
I'm sorry, but I like the basic screen.
so I remove blow init.el. 

;; (require 'crafted-startup)
;; (unless crafted-startup-inhibit-splash
;;   (setq initial-buffer-choice #'crafted-startup-screen))

in a different way
It would be nice to bring up the startup screen from config.org.

**Comment by ajxn** [comment]
So, the problem is when you start the `emacs` and the daemon or when you start the `emacsclient`.

**Comment by meleein1** [comment]
> So, the problem is when you start the `emacs` and the daemon or when you start the `emacsclient`.

oh. sorry.
Daemon start no problem.
run (emacsclient --create-frame --alternate-editor="") have warning.
run emacs no problem. No Daemon, run emacs no problem.

**Comment by jeffbowman** [comment]
The problem is the calculation to attempt to center the welcome text results in a negative number.  I'll look into this.  I run Emacs as a daemon all the time, this isn't an issue I have run into. 

@meleein1 it would be helpful if you could update here with the value for `(window-width)` when you get the warning. 

Thanks!

**Comment by jeffbowman** [comment]
@meleein1 I have applied a fix, please pull the update and let us know how it goes. Reopen this issue if it is not fixed.

**Comment by meleein1** [comment]
great!
warnings disappear.
My obsessive compulsion is disappear.
