### ISSUE TITLE
Wish: Video about org tables

### ISSUE THREAD

**Issue by buhtzz** [SystemCrafters/crafted-emacs#231]
Hi David,

thanks a lot for your great work and videos.

What I essentially miss is a video about tables in org mode. Of course there are a lot of such videos out there but none of them have the David-Wilson-Sugar. ;)

The point is you often don't only show what is possible but you often show how to use something in an efficient way. Currently I don't see a way to use them efficient. I don't want to calculate something. I just want to write a table with content. But even this is so "complex" that I end up using multiple levels of headings instead of a table. ;)

**Comment by jeffbowman** [comment]
Not stealing @daviwil thunder on making videos, but this one by Rainer Konig is pretty good, if a bit on the old side: https://youtu.be/JHKrTsiz4JU.  Maybe that will help you?

**Comment by buhtzz** [comment]
I don't like that video because he shows how fancy that feature is and invests to much time in using tables like Excel.

I simply want to write a table *with multiline cell content*. I know this is possible but it seems it is so hard and wired that there is now efficient way for it. Only David can find a way if there is one. ;)

**Comment by jeffbowman** [comment]
I'm curious about your definition of `efficient`, but we'll see if David will put something together for you.

**Comment by jeffbowman** [comment]
Closing, not really related to Crafted Emacs.
