### ISSUE TITLE
Use tabspaces to implement crafted-workspaces

### ISSUE THREAD

**Issue by ParetoOptimalDev** [SystemCrafters/crafted-emacs#233]
Alongside consult with 'b' and 'p' narrowing keys this is kind of a one-liner.

In my config I default to only listing buffers in tabspace, then use the 'b' narrowing key in consult to see all buffers. 

I suppose crafted-workspace would also want default keybindings too. That would make this more than a one-liner.

**Comment by jeffbowman** [comment]
I'm not sure what you mean here.  Are you talking about configuring tabs across the top of Emacs to hold buffer configurations? (maybe `tab-bar-mode` or `tab-line-mode` ?) Not sure what you mean by tabspace. Perhaps you could clarify?

**Comment by ParetoOptimalDev** [comment]
Oh my... I didn't give a link or specify that "tabspaces" was a package. Here it is:

> Tabspaces leverages tab-bar.el and project.el (both built into emacs 27+) to create buffer-isolated workspaces (or “tabspaces”) that also integrate with your version-controlled projects.

https://github.com/mclear-tools/tabspaces

Basically it seems to be very close to or a large part of how `crafted-workspace` would be implemented.

**Comment by jeffbowman** [comment]
That is an interesting project indeed! Maybe you could submit a PR?

**Comment by ParetoOptimalDev** [comment]
Yes, I might be able to do that this weekend. I believe this kind of workspace functionality would be pretty valuable to share.

**Comment by mclearc** [comment]
Author of tabspaces package here. I'm not sure whether this will be helpful but you can see how I setup tabspaces here: https://github.com/Lambda-Emacs/lambda-emacs/blob/main/lambda-library/lambda-setup/lem-setup-tabs.el

I also have a basic "workspaces" workflow setup here: https://github.com/Lambda-Emacs/lambda-emacs/blob/main/lambda-library/lambda-setup/lem-setup-workspaces.el

You're all welcome to pull anything from this you find useful. Unfortunately I don't have the time to do a proper PR right now.
