### ISSUE TITLE
crafted-package-install-package should defer until package list is refreshed.

### ISSUE THREAD

**Issue by Cerebus** [SystemCrafters/crafted-emacs#236]
On startup, if the package list is stale crafted-package starts a background refresh.

Local modules that call `crafted-package-install-package` before the refresh completes use the stale package list, and fail if package version no longer exists in the package archive.

This breaks init, so the package list isn't updated, so it's still stale on next start.  Lather, rinse, repeat.

Calling package-refresh-contents interactively doesn't seem to help, possibly because I'm using chemacs?

Or am I missing something?

**Comment by Cerebus** [comment]
Trying to get past this, I dropped the nuisance package temporarily, and --
- The package list is *always* stale on every startup.
- crafted is always compiling packages.
Yes, I'm up to date with current master.

**Comment by jeffbowman** [comment]
I'm trying to duplicate this.  Here is my configuration: 
`(("236" . ((user-emacs-directory . "/home/vagrant/crafted-emacs-236/crafted-emacs")
           (env . (("CRAFTED_EMACS_HOME" . "/home/vagrant/crafted/236")))
	   )))`

my config.el
``` emacs-lisp
(require 'crafted-mastering-emacs)

(crafted-package-install-package 'flymake-proselint)
(crafted-package-install-package 'corfu)
(crafted-package-install-package 'ack)
```

but I am not seeing the problem you are having.  Can you provide your chemacs2 config and I'll keep trying? 

Also, I did make a change to the bootstrap code to make sure the `elpa` directory is created if not present.  This may help, so if you could pull those updates and try again? 

Thanks for the report!

**Comment by Cerebus** [comment]
I nuked all the elpa caches everywhere (chemacs, crafted, and crafted config) and I seem to be back working again.
