### ISSUE TITLE
using emacs 27.1 version user can't load crafted-emacs-mastering.el.

### ISSUE THREAD

**Issue by meleein1** [SystemCrafters/crafted-emacs#237]
When I Try to use crafted-emacs-mastering module, failed.
I think (fido-vertical-mode 1) problem.

anyone use emacs 27.1 version?

I think after emacs 28.1 version Use Ok that module. but 27.1 version users can't Use.

27.1 users maybe use icomplete-mode and ido-mode.

how about this issue.

I reference this.
http://xahlee.info/emacs/emacs/emacs_icomplete_mode.html

**Comment by jeffbowman** [comment]
Ah, right... `fido-vertical-mode` is new in 28. I keep forgetting some people may not have upgraded yet. I'll add the appropriate check.

**Comment by jeffbowman** [comment]
Fix applied, please pull from master and try again. 

Thanks for the report!
