### ISSUE TITLE
Symbol's function definition is void crafted-package-install-package

### ISSUE THREAD

**Issue by Cerebus** [SystemCrafters/crafted-emacs#244]
- emacs 28.2 on Debian 11
- Native compilation enabled
- Chemacs2 with `CRAFTED_EMACS_HOME` set
- New clone of Crafted Emacs in `user-emacs-directory`
- Empty `early-config.el`

`config.el`:
```
(require 'crafted-completon)
(require 'crafted-compile)
```

What I actually did was add `crafted-completion` and waited for native compile to complete, then added `crafted-compile`.  The async  native compile log shows exactly one warning about an unbound var in `corfu-doc-mode`.

On restart with `crafted-compile` added to `config,el`, `*Async-native-compile-log*` contains:
```
Compiling /home/cerebus2/.config/crafted-emacs/config.el...
/home/cerebus2/.config/crafted-emacs/config.el: Error: Symbol's function definition is void crafted-package-install-package
Compiling /home/cerebus2/.config/crafted-emacs/early-config.el...
/home/cerebus2/.config/crafted-emacs/early-config.el: Error: empty byte compiler output nil
Compilation finished.
```

No stack trace with `debug-init`.

**Comment by Cerebus** [comment]
I noticed that when this happens, the `embark` doesn.t work (`C-h k C-.` reports as a self-insert command); however, in the minibuffer `embark-act` is tagged with the `C-.` binding.  

I really don't grok what's happening.

**Comment by Cerebus** [comment]
I ripped out Chemacs2, so crafted is cloned to `.emacs.d` and `config.el` in `~/.config/crafted-emacs` and it's all still busted.

This is an absolute minimal configuration, so .. what am I missing?

**Comment by jeffbowman** [comment]
Thanks for the report.  This is very odd.  That said, I don't use native compile mode myself, so, let me get that turned on and see what I can learn. 'Tis a real head scratcher.

**Comment by jeffbowman** [comment]
Not really an answer, but perhaps a work-around... It seems that during startup, each file is compiled in a pristine environment which means the `crafted-config-path` would not have been declared.  However, if you run `(native-compile "~/.config/crafted-emacs/config.el")` from inside a running Emacs, the error is not output, and, having compiled it, the next time Emacs starts, no error emits.  So, continuing with the hypothesis, when doing the compile from a running Emacs, the variable is known while the compiler is running.

**Comment by Cerebus** [comment]
Yeah, tracking,  The way to resolve this would seem to be to pull all the defines out of `init.el` and put them somewhere that will get loaded with other dependencies.  Bootstrap would seem to be the right place.

**Comment by jeffbowman** [comment]
Perhaps.  Bootstrap is (was?) intended to be where we configured packaging systems.  No technical reason we could put the vars there and `(require ...)` in both `early-config.el` and `config.el`.  Do you have a PR for this?

**Comment by jeffbowman** [comment]
Is this still a problem with Emacs 29+?  Can anyone confirm?  The work-around I mention is still valid, so do we need this issue?

**Comment by jeffbowman** [comment]
No response for several weeks, also Crafted Emacs v2 has been released, so closing this
