### ISSUE TITLE
doom-modeline interfering with eglot+gopls

### ISSUE THREAD

**Issue by Cerebus** [SystemCrafters/crafted-emacs#246]
With doom-modeline *loaded*, eglot+gopls loses its mind (specifically, it seems to stop updating except on buffer save).  This basically makes gopls in go-mode a dead thing.  With doom-modeline *unloaded*, eglot+gopls works as expected.

See #44 as maybe a workaround.

Reproduction:
- Enable go-mode with eglot (I'm using the following).
```
(crafted-package-install-package 'go-mode)

(add-hook 'go-mode-hook #'eglot-ensure)
(autoload 'go-mode "go-mode" "A major mode for Golang" t)

(add-to-list 'auto-mode-alist '("\\.go\'" . go-mode))
(add-to-list 'before-save-hook #'gofmt-before-save)
```
- Comment out https://github.com/SystemCrafters/crafted-emacs/blob/a0a8371053f0498e4619389580d28c578f1f710c/modules/crafted-ui.el#L75

- Load a golang source and attempt a completion of ... anything at all.

- Enable `doom-modeline-mode` and reload the go source buffer, and try a completion.

**Comment by Cerebus** [comment]
I should stress, this is with the mode *loaded*, not *enabled*.  If you do the above and *disable* doom-modeline-mode, even reloading the buffer doesn't restore function.

**Comment by Cerebus** [comment]
.... aaaand when I go `-Q` and manually load up doom-modeline, go-mode, and eglot, everything works as expected.

**Comment by Cerebus** [comment]
Issue is breaking changes in eglot that haven't made it into doom-modeline stable.

https://github.com/seagle0128/doom-modeline/issues/590

The workaround is to disable `package-menu-hide-low-priority` and install the unstable version.

**Comment by jeffbowman** [comment]
#44 has been around for quite a while, there were a couple attempts at closing it, but they never found their way into the system.  I left it open hoping it would give someone else an opportunity to get involved.  That never happened, so I have resolved that issue. Doom modeline is now optional and off by default. If you want it back on, customize the `crafted-ui-use-doom-modeline' to have a value of `t'.

**Comment by erikLundstedt** [comment]
> #44 has been around for quite a while, there were a couple attempts at closing it, but they never found their way into the system. I left it open hoping it would give someone else an opportunity to get involved. That never happened, so I have resolved that issue. Doom modeline is now optional and off by default. If you want it back on, customize the `crafted-ui-use-doom-modeline` to have a value of `t`.
> 
> Cc: @Cerebus @daviwil

is this implementing my fix as talked about [here](https://github.com/SystemCrafters/crafted-emacs/issues/44#issuecomment-1239110255) or as found in my own config repo, Or is it simply making the doom modeline package optional(booth options are good)

maybe put a short version of above(quoted comment)in #44
