### ISSUE TITLE
Eglot stomps on flymake-diagnostic-functions

### ISSUE THREAD

**Issue by Cerebus** [SystemCrafters/crafted-emacs#250]
When eglot takes over a buffer, it replaces all entries in flymake-diagnostic-functions.  If your LSP has linting, you won't notice, but with LSPs like pyright you lose the mode's built in diagnostics.  

For python-mode, I'm currently using the following, and it seems to work.

```emacs-lisp
(defun my/eglot-python-fixup ()
  (add-hook 'eglot-managed-mode-hook (lambda () (add-hook 'flymake-diagnostic-functions #'python-flymake t t)))
  )

(add-hook 'python-mode-hook #'my/eglot-python-fixup)
```

Adapted from [this](https://www.reddit.com/r/emacs/comments/s96wec/comment/ii6norq/?utm_source=share&utm_medium=web2x&context=3).

A general fix that captures the mode's value and adds it to back to flymake-diagnostic-functions after the call to eglot-ensure is probably possible, but I haven't tried this yet.

**Comment by jeffbowman** [comment]
I'll look into this as well, I hadn't noticed this problem in my usage.

**Comment by jeffbowman** [comment]
Did you try `(add-to-list 'eglot-stay-out-of 'flymake)` to keep eglot from clobbering flymake functions?

**Comment by Cerebus** [comment]
It's an either-or.  If you want the LSP results in Flymake (and you do), then you can either tall eglot to stay out of flymake and add eglot to the diagnostics list, or you can hook eglot to put the mode diagnostics back after eglot initializes a buffer. 

[Seems like this is a reasonable approach, though.](https://github.com/joaotavora/eglot/discussions/1122)

Personally I think it'll be easier to manage the odd cases on a per mode basis, since it's only going to be an issue with specific LSPs.

Maybe this just belongs as a documentation snippet in crafted-ide docs?
