### ISSUE TITLE
Updated Crafted-Emacs breaks due to corfu-popupinfo

### ISSUE THREAD

**Issue by aberges-grd** [SystemCrafters/crafted-emacs#258]
The new crafted-completion module update has a `(require 'corfu-popupinfo)`. However, when opening Emacs after this upgrade, it says it can't find the file. AFAIK corfu-popupinfo is part of corfu, so idk why it doesn't find it (unless it was added very recently and updating Crafted Emacs doesn't update the core packages).

**Comment by jeffbowman** [comment]
What package manager are you using?  If you are using `straight.el` then you need to make sure you have pulled from here recently as there is a fix to add the `extensions` folder to the load path to find this extension.  If you are using `package.el`  the extensions are already included in the package, so maybe you need to update your installed packages (`list-packages`, mark the upgrades with `U` and then execute the changes with `x`). 

Does that help?

**Comment by aberges-grd** [comment]
Hi, I am using package.el and yes, updating with list-packages worked.
It's been so long since I last used the native emacs package capabilities that I had forgot about that.
Thanks!

**Comment by johnhamelink** [comment]
I use Straight with crafted-emacs like so:

```lisp
(defmacro crafted-package-install-package (package)
  "Install PACKAGE using straight."
  `(straight-use-package ,package))
```

In order to be able to overcome this issue, I need to pull Vertico and Corfu before `(require 'crafted-completion)`:

```lisp
(straight-use-package
 '(vertico :files (:defaults "extensions/*")
           :includes (vertico-buffer
                      vertico-directory
                      vertico-flat
                      vertico-grid
                      vertico-indexed
                      vertico-mouse
                      vertico-multiform
                      vertico-quick
                      vertico-repeat
                      vertico-reverse
                      vertico-unobtrusive)))

(straight-use-package
 '(corfu
   :type git
   :host github
   :repo "emacs-straight/corfu"
   :branch "master"
   :files (:defaults "extensions/*")
   :includes (corfu
              corfu-echo
              corfu-history
              corfu-indexed
              corfu-info
              corfu-popupinfo
              corfu-quick)))
```
