### ISSUE TITLE
crafted-screencast is broken after latest update to https://github.com/tarsius/keycast

### ISSUE THREAD

**Issue by ingorichter** [SystemCrafters/crafted-emacs#262]
With [commit](https://github.com/tarsius/keycast/commit/1c92a5daf535c5481803ea781b65517a136b60c9) the mode was renamed from `keycast-mode` to `keycast-mode-line-mode`. This change breaks the current `crafted-screencast.el` implementation.
I'm using `straight` for package management. Users who rely on the melpa version will be impacted once they update their packages to the latest version

**Comment by jeffbowman** [comment]
Thanks!  Just curious, there is [this line](https://github.com/tarsius/keycast/commit/1c92a5daf535c5481803ea781b65517a136b60c9#diff-e91118238c21e5990640151524626efa7972e2181c117fde3d39dd610d6f1b84R396) (line 396 in the diff) which defines an alias and should help not break things, I am assuming you are getting an error in spite of this line?

**Comment by ingorichter** [comment]
hm, good point. Despite that alias I'm getting the error 🤔

**Comment by jvdydev** [comment]
From my testing, there seem to be two ways of fixing it (ignoring the broken guard):
```emacs-lisp
;; explicitly require
(when ; guard
  ;; configuration ...
  (require 'keycast)
  (keycast-mode))
```

```emacs-lisp
;; use keycast-mode-line-mode (keycast-mode is available afterwards)
(when ; guard
  ;; configuration ...
  (keycast-mode-line-mode))
```

The reason `keycast-mode-line-mode` is the new autoload (renamed from `keycast-mode`), but the alias `keycast-mode` is not an autoload.
Requiring the package fixes it, but since it's already broken, moving to the new name is probably the better solution.

**Comment by jvdydev** [comment]
I'm closing this as the error should be resolved.
