### ISSUE TITLE
Q:   can users call (crafted-package-install-package)?

### ISSUE THREAD

**Issue by pablos-here** [SystemCrafters/crafted-emacs#265]
Hi,

While you may have heard it before, it cannot be stated too many times that this project is amazing.  Thank you!

As I'm porting my `init.el` to `custom.el`, I'm at a cross roads on how to pull in new packages.  

I looked at some of the project modules and see that they make use of `(crafted-package-install-package)` macro.  As it is mentioned in #260, I see the macro provides a level of abstraction between `straight.el` and `package.el`.

As I'm fundamentally lazy (although it appears long winded!), is it okay for users to call  `(crafted-package-install-package)`?  I suppose there's no guarantee that the call signature won't change in the future.

What I like about using it is that it provides some level of insulation to my `custom.el`.

**Comment by jeffbowman** [comment]
You are welcome to call `crafted-package-install-package` in your configuration.
