### ISSUE TITLE
Compilation error when installing tree-sitter-langs

### ISSUE THREAD

**Issue by pablos-here** [SystemCrafters/crafted-emacs#266]
Hi,

On a fresh install, I'm getting a compilation error when I attempt to install the `tree-sitter-langs` package.

Below is a stripped down `custom.el` test case along with the `*Compile-Log*` error message.

To set up the test case:

- Ensure there is no `~/.crafted-emacs/`
- Git (pun?!)  the latest code (in my case, `~/.emacs.d`)
- Seed `~/.crafted-emacs/` by starting emacs and exiting.
- Create `~/.crafted-emacs/custom.el` with the contents below
- Start emacs to generate the issue

Please let me know if you need more information.

Thx!

```
;;; custom.el --- Dismiss startup message            -*- lexical-binding: t; -*-

(provide 'custom)

(crafted-package-install-package 'tree-sitter)
(crafted-package-install-package 'tree-sitter-langs)
```

```
Compiling internal form(s) at Mon Jan  2 18:05:47 2023
Leaving directory ‘/home/borked/.crafted-emacs/elpa/tree-sitter-langs-0.12.10’

Compiling file /home/borked/.crafted-emacs/elpa/tree-sitter-langs-0.12.10/tree-sitter-langs-build.el at Mon Jan  2 18:05:47 2023
Entering directory ‘/home/borked/.crafted-emacs/elpa/tree-sitter-langs-0.12.10/’

Compiling file /home/borked/.crafted-emacs/elpa/tree-sitter-langs-0.12.10/tree-sitter-langs.el at Mon Jan  2 18:05:47 2023
Error (bytecomp): Error calling (tar -xvzf tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.10.tar.gz), exit code is 2
```

**Comment by jeffbowman** [comment]
The problem is upstream, see [this issue](https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154).  If you are using `straight.el` or `quelpa` or `package-vc` (from Emacs29) you can pull the suggested commit to resolve the issue.

**Comment by jeffbowman** [comment]
> The problem is upstream, see [this issue](https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154). If you are using `straight.el` or `quelpa` or `package-vc` (from Emacs29) you can pull the suggested commit to resolve the issue.

UPDATE: The issue was closed with a fix, but no release has been made yet.

**Comment by jeffbowman** [comment]
> A new release is now out and it should be back to working.

UPDATE 0.12.12 has been released
