### ISSUE TITLE
Multiple "obsolete timestamp with cdr 1" messages at startup

### ISSUE THREAD

**Issue by dbuscher** [SystemCrafters/crafted-emacs#268]
The obsolete timestamp error message appears 40 times during startup. No obvious problems caused except for the error messages.

I am running the example config.el on emacs 28.1/28.2, MacOS. The emacs debugger narrows the source of the messages down to the function crafted-package-archive-stale-p, called from crafted-package-initialize. The former function was edited on Dec 17, so it seems likely these edits have caused the problem, but my emacs-lisp-fu is not sufficient to pinpoint the exact cause.

**Comment by jeffbowman** [comment]
The issue was reported and is fixed in Emacs 29.  It is an odd bug that shows up in this code when we are checking if 
 the package archives are stale:

```emacs-lisp
(time-less-p (encode-time (decoded-time-add last-update-time delta))
                     (encode-time today))
```

specifically the `encode-time` function.  It doesn't actually seem to break anything, just outputs some weird warnings.

**Comment by dbuscher** [comment]
OK, I'll upgrade to Emacs 29 when I have time and in the meantime learn to stop worrying!
