### ISSUE TITLE
Compile error when `crafted-compile´ enabled

### ISSUE THREAD

**Issue by pablos-here** [SystemCrafters/crafted-emacs#271]
Hi,

The `crafted-compile`  chirps the following in the `mini-buffer` when `~/.crafted-emacs/{early-config.el,config.el` are not found:

> Native compiler error: "Path not a file nor directory", "/home/XXX/.crafted-emacs/early-config.el"

# Set up

<details>
<summary>Click to expand</summary>

- Clone the latest bits to `~/.emacs.d`
- Start with an empty `~/.crafted-emacs` directory
- Start `Emacs` to seed the `~/.crafted-emacs` directory
- Create  `~/.crafted-emacs/custom.el` using the `elisp` below
- Start `Emacs` to download the corresponding packages
- Exit `Emacs`

</details>

# Tests
## No issue

- Continuing from `Set-up`, start `Emacs`.  
- Notice there are no issues.

## Issue

- Un-comment `(require 'crafted-compile)` 
- Start `Emacs` - note the warning.  From `*Messages*`:

> Compiling file(s): (/home/XXX/.crafted-emacs/early-config.el /home/pablo/.crafted-emacs/config.el)
> native-compile-async: Native compiler error: "Path not a file nor directory", "/home/XXX/.crafted-emacs/early-config.el"

# `custom.el`
<details>
<summary>elisp</summary>

```elisp
(provide 'custom)

;; ========================================================================
;; The list of System Craft modules we may load.  Please see the module
;; for additional settings.
;; ========================================================================
(require 'crafted-defaults)    ; Sensible default settings for Emacs
(require 'crafted-updates)     ; Tools to upgrade Crafted Emacs
(require 'crafted-completion)  ; selection framework based on `vertico`
(require 'crafted-ui)          ; Better UI experience (modeline etc.)
;;(require 'crafted-windows)     ; Window management configuration
(require 'crafted-editing)     ; Whitespace trimming, auto parens etc.
(require 'crafted-lisp)
;;(require 'crafted-evil)        ; An `evil-mode` configuration
(require 'crafted-org)         ; org-appear, clickable hyperlinks etc.
(require 'crafted-project)     ; built-in alternative to projectile
(require 'crafted-speedbar)    ; built-in file-tree
;;(require 'crafted-screencast)  ; show current command and binding in modeline
;;(require 'crafted-compile)
;;(require 'crafted-erlang)
(require 'crafted-ide)
;;(require 'crafted-latex)
;;(require 'crafted-mastering-emacs)
;;(require 'crafted-osx)
;;(require 'crafted-pdf-reader)
(require 'crafted-python)
(require 'crafted-startup)
(require 'crafted-workspaces)
```

**Comment by jeffbowman** [comment]
Thanks for the report, should be fixed now.  Please pull and retest.  You can reopen if needed.

**Comment by pablos-here** [comment]
Fix confirmed.  

Thank you so much!
