### ISSUE TITLE
module request:  Android

### ISSUE THREAD

**Issue by gtusr** [SystemCrafters/crafted-emacs#274]
SystemCrafters is an excellent set of tutorials, and I wish that it could become part of the standard distribution.

A GUI-based emacs for Android has recently been released on github that works quite well, but there are a number of configuration issues that need to be worked out on this new platform that would be nice to document in a module as well.

**Comment by jeffbowman** [comment]
That seems reasonable.  Can you provide such a module and some documentation for it?  I don't use Emacs on Android, so I'm not likely to be the one to provide such a module.  I'd love to see it come from the community though!

**Comment by jeffbowman** [comment]
Closing, no movement on this, V2 has been release.
