### ISSUE TITLE
Version in crafted-evil-packages should be without quotations

### ISSUE THREAD

**Issue by hippm** [SystemCrafters/crafted-emacs#276]
Hey,

i'm using your crafted packages and found a potential Bug in crafted-evil-packages:

The version-number "28" in the when-statement should be without quotations so that its an integer. I had to change it or it wouldn't load

https://github.com/SystemCrafters/crafted-emacs/blob/2dca264fc3abe6c4050264d66a11cc673ac9311b/modules/crafted-evil-packages.el#L20

**Comment by jeffbowman** [comment]
Thanks for the report, this is fixed on the `craftedv2beta` branch with  this commit 4b1f316.  Closing this issue.
