### ISSUE TITLE
history file location is being changed after savehist-mode is loaded

### ISSUE THREAD

**Issue by F271wQbGjWSC** [SystemCrafters/crafted-emacs#277]
If you use a non default location for storing your config (like the ~/.config/crafted...etc example), this creates a scenario where savehist loads history from the default location at startup and writes to the non default location during the session.

https://github.com/SystemCrafters/crafted-emacs/blob/f7c6abae32726e4f38e4cf103a931a9af605a76f/modules/crafted-defaults.el#L95

**Comment by jeffbowman** [comment]
This is an interesting comment, I haven't noticed this behavior.  The only place I see a "history" file exists is in the expected `crafted-emacs/var/` directory, and I still see history loaded from that file.  I'll see if I can replicate what you are saying, but perhaps you could add some additional details like version of Emacs you are using and possibly a minimal config that shows the problem?

**Comment by jeffbowman** [comment]
No followup on this issue, with the pending release of Crafted Emacs v2, closing this issue.
