### ISSUE TITLE
Have a way to check if a package is installed

### ISSUE THREAD

**Issue by JulienTant** [SystemCrafters/crafted-emacs#28]
In order to provide `rational-emacs` as much flexibility as possible, we need to find a way to test if a package is installed even if the package is not currently loaded.

Examples of use case:
- create a generic key binding configuration that depends on the package being installed.
- setting some extra configuration when two packages are installed and can work together with some configuraiton.

I tried using emacs's `featurep` but it does not detect installed packages that are not loaded (as in explicitly or `require`'d by a another package).

Keeping in mind that packages can be installed through straight or through the user's package manager (GNU Guix, nix, pacman/aur, apt...)

emacs might already have an existing function for this.

For context: https://github.com/SystemCrafters/rational-emacs/pull/16

**Comment by jeastman** [comment]
I am not certain the concept you are talking about exists with straight. Have a look at the documentation of `straight-remove-unused-repos`.

    Remove unused repositories from the repos directory.
    A repo is considered \"unused\" if it was not explicitly requested via
    `straight-use-package' during the current Emacs session.

Using `straight-use-package` during a session will "Register, clone, build, and activate a package and its dependencies." Therefore `featurep` should be the correct thing to do (if we don't care about "unused" packages).

**Comment by sthesing** [comment]
Should be resolved by the PRs mentioned in #313. 
See #294 for the discussion.
