### ISSUE TITLE
[craftedv2beta] crafted-org contains both denote and org-roam

### ISSUE THREAD

**Issue by jvdydev** [SystemCrafters/crafted-emacs#283]
More of a discussion question/point I noticed while trying out the v2 beta:

The new `crafted-org` module contains package definitions for both `org-roam` as well as `denote`.
While not identical, they provide similar-enough functionality (as pointed out in the comments in `crafted-org-packages.el`) that most people will probably not use both.

`org-roam` requires a C compiler to compile the SQLite binary (and by extension another thing running).
For the Linux/BSD users that's usually not a problem, but other OS'es or situations may not allow (or require additional setup for) the installation of a C compiler (not sure, but probably affects for example #274).
Not sure how much the SQLite usage as a whole eats into the idea of keeping everything "close to built-in".

`denote` on the other hand offers a lot less comfort functions (e.g. no built-in equivalent to `org-roam-node-find`).

My proposal would probably be to have denote as a default and add documentation on org-roam (including the additional requirement(s) and maybe a simple example configuration).

**Comment by jeffbowman** [comment]
This is a good suggestion.  `denote` lines up more closely with the principles of this project.   `org-roam`, on the other hand, is widely used, so I thought putting both in the configuration would satisfy more users.  

In Emacs 29, there is an option to build Emacs with `sqlite`, so the C compiler isn't needed later, only the libraries which may need to be installed by the user independently of Emacs.  At least that is how I understand it.  That doesn't solve the problem for Android users per se, but for users on other platforms, they shouldn't need a C compiler (when using the (hopefully) imminently release Emacs 29).  For users of Emacs prior to version 29, though... well, that's a different story. 

I wonder if you'd be willing to provide a PR to support your suggested change?

Thanks for the suggestion!

**Comment by jvdydev** [comment]
I'd be happy to work on this, however I think providing docs for crafted-org would also make sense (while also removing `org-roam` and it's related configuration from the actual module).
Should I work on that as a whole or split it out into two PRs?

**Comment by jeffbowman** [comment]
Thank you very much!  I look forward to your work! I would prefer separate PRs if that isn't too much of a hassle on you.

**Comment by jvdydev** [comment]
I experimented around a bit more in a container regarding the C compiler dependency and it seems that even with the current emacs-29 branch, a C compiler is still required for org-roam.

That may change when Emacs 29 is more readily available and org-roam gets an update to use the internal sqlite interface.

In any case, changes are in the work, I'll make the PRs soon.

**Comment by jeffbowman** [comment]
Closing as this is resolve in #286
