### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by davdent** [SystemCrafters/crafted-emacs#291]
No icons are showing. I am on Ubuntu 23.04 using Emacs 28.2 and Chemacs2. I have installed the fonts, which end up  in ~/.local/share/fonts.  

Should the icons automatically show for different modules and packages or do I need to add code to activate them? Could there be a path issue on my system? I have tried adding a load path to the fonts directory, but this does nothing. 

Thanks in advance for help on this.

**Comment by jeffbowman** [comment]
Not sure I understand the question.  What icons are you expecting to see that you aren't?

**Comment by davdent** [comment]
My bad! As a relative newbe and Doom refugee I wrongly assumed that if the all-the-icons package is being installed (by the crafted-ui module) that this is all I need. Have since learned of the various additional packages required to make the icons actually work. All is well and we can close this issue. Thanks.

**Comment by jeffbowman** [comment]
Thanks for letting us know!
