### ISSUE TITLE
evil movement with logical visual lines rather than screen lines

### ISSUE THREAD

**Issue by davdent** [SystemCrafters/crafted-emacs#293]
Currently, when editing in org mode with evil keys, line movement with "j" and "k" is by screen live. "A" sends the point to the end of the screen line. Instead of this behaviour, I would like to have evil line movement in text applications such as org-mode set to use logical rather than screen lines, which is the default, I believe. This includes having the "A" command move the point to the end of the logical line. I have tried the following:   

> (setq  'evil-respect-visual-line-mode nil) 

and then tried editing crafted-evil.el to:
> (customize-set-variable 'evil-respect-visual-line-mode nil)

to no avail. Any help on getting this to work would be appreciated. 

Note: I am using emacs 28.2 and running crafted-emacs under Chemacs2.

**Comment by davdent** [comment]
A small update on this issue. Using  the A key now goes to the end of the logical line. Not sure why it is working now, or why it wasn't before.

**Comment by jeffbowman** [comment]
The last comment seems to indicate this issue is resolved.  Closing.
