### ISSUE TITLE
[craftedv2beta] Getting Started section in README

### ISSUE THREAD

**Issue by jvdydev** [SystemCrafters/crafted-emacs#305]
The current Getting Started section in the README doesn't cover `early-init.el` (potentially leading to confusion).

Not sure if this section should just be expanded or *just* link to the Getting Started Guide.
Thoughts?

**Comment by jeffbowman** [comment]
I'm okay with it being missing on the README.  There is the text about "more detailed examples".  Maybe the wording could be better if it isn't clear.  I was trying to keep the README to something someone would actually read with links to more information in other documentation (like the "getting started guide"). 

I would be concerned about anything that leads to confusion, so I'm open to ideas on improving the README.

**Comment by jvdydev** [comment]
I was mainly thinking to only linking to the Getting Started Guide, but that may be a bit too sparse? Not sure

**Comment by jeffbowman** [comment]
I think its fine.  It's the simplest possible startup.  It links to the getting started guide and there is information there about `early-init.el`
