### ISSUE TITLE
[craftedv2beta] Startup config module

### ISSUE THREAD

**Issue by bacchist** [SystemCrafters/crafted-emacs#308]
It does not set initial-buffer-choice, and it is unclear that it is required. It took me a while to figure out why it wasn't working because it's not documented anywhere except in an example init file that shows it being set (unless I overlooked something). I think this can be made the default anyway, since we can infer this is the user's intent from the fact they've added the module to their config.

Also there is a fairly ambiguous error message saying "Crafted Emacs status could not be determined" which appears to be related to the broken crafted-updates-config. That error can be suppressed or replaced pending a fix.

**Comment by jeffbowman** [comment]
There are 2 issues here, thanks for bringing them up, we'll look into them.  It is helpful if you can focus issues to one topic that way we can track individual fixes and tie those directly to the related issue. 

The `initial-buffer-choice` value can be introspected with `M-x describe-variable`, and if you have the Emacs Lisp manual installed, there is a section which documents that particular variable (in a `*Help*` buffer, press `i` to jump to the relevant info page).  We can add a comment to the code to mention it's usage, and possibly improve the docstring to the appropriate defun where the splash screen is defined.  I'll look into this. 

Regarding the second, could you open a second issue, turn on `debug-on-error` and then provide any stack trace you might get when you see that error?  That would be very helpful!

Thanks for the report!
