### ISSUE TITLE
texinfo tags in docs

### ISSUE THREAD

**Issue by bacchist** [SystemCrafters/crafted-emacs#311]
Github doesn't process tags such as `@@texinfo:@emph{}@@`, so they just get displayed as part of the text. Kind of a minor issue, but many users will use Github to view the docs, especially when getting started.

**Comment by jeffbowman** [comment]
Yep.  I haven't found a good way to get the markup correct in both places.  This was a compromise as it marginally detracts from the experience in GitHub, but reads well in info which allows offline usage.  Open to suggestions (and PRs) to improve the docs formatting so it looks good both online and in the Emacs built-in info browser.

**Comment by sthesing** [comment]
Closed by #360
