### ISSUE TITLE
[craftedv2beta] Question regarding the skeleton for new modules

### ISSUE THREAD

**Issue by sthesing** [SystemCrafters/crafted-emacs#334]
Hi everyone,

while drafting documentation for the `crafted-init-config` module, I wondered about the `auto-insert-mode`-skeleton for new crafted modules. I have two questions:

1. Currently, it is only triggered when the new file is created inside `crafted-emacs-home`. So only users who hack on the modules of the Emacs instance their currently using benefit from the skeleton. Users how prefer separate project folders and run separate Emacs instances for testing can't use the skeleton in their working environment.
So, **first question**: Wouldn't it be preferable to let the user either specify a list of directories or to simplify the condition to the form "modules/crafted-*\\.el"?
2. My **second question** is: Does this belong in the `crafted-init-config` module at all? It is probably the one module we expect the vast majority of users to load. Wouldn't it be more aptly located in something like `crafted-contribute-config`?

**Comment by sthesing** [comment]
Hi @jeffbowman,

thanks for the reply. That was really helpful.

#### Question 1
> We could try simplifying the form to `"modules/crafted-*\.el"`, that might be a reasonable compromise. That said, we would need to test to make sure we aren't running the skeleton in the users `custom-modules` folder, that is their folder and the skeleton would be (in my opinion) inappropriate in files in that folder.

Oh yeah, I didn't think of `custom-modules`, even though I use it myself. (My modules don't start with "crafted", though.)
If we use `.*/modules/crafted-*\.el`, we'd only offer the auto-insert in folders called "module" for files started with "crafted-". And to be quite sure, we could make this the default value of a customization variable and document how users who are bothered by this can change it or turn it off entirely.

#### Question 2
> It is in the `crafted-init-config` module as that is a (nearly) guaranteed module to get loaded by every user (as you point out), so the user would not have to add any further configuration to develop new modules. 

Which, come to think of it, probably makes sense for a community of crafters.

> It causes no harm for users who never create a new Crafted Emacs module. In Crafted Emacs v1, this was in the `init.el` file for similar reasons. [...] does it really matter where the skeleton lives? It currently costs almost 0 time to leave it where it is.

I'm not at all against that, and no, it really doesn't matter where that skeleton lives. I'm asking that questions from a documentation point of view: What is the common theme of the functionality here?
And your reply gave me a viable idea for that: much of `crafted-init` is module related (getting them to run, developing new ones, custom-modules, provide documentation etc.). Does that make sense? 
So if there ever was a problem to solve, it was a documentation problem. And I feel that's solved by your reply.

> In this case moving to a `crafted-contributing-config` would have what in it? At the moment, the skeleton under discussion, but what else? 

The only thing I can think of is a corresponding auto-insert skeleton for writing module documentation. In the future, things like unit tests for the modules might also go here. But as long as we don't have anything like that, it probably doesn't make sense to make changes like that.

Again, thanks. 
And if you and @jvdydev also think that making `.*/modules/crafted-*\.el` the default value of a new customization variable, I'll prepare that along with the codumentation for that module.

**Comment by jvdydev** [comment]
I'm not 100% sold on whether it's really necessary to customize that specific insertion personally.

I could see the use-case for testing out modules in one's `custom-modules` section, then longer-term contributing them upstream, however I'm not sure that new modules are necessarily a frequent occurrence (to where one would want this customized).
Other than that, I don't think many people want to re-use an auto-insert that has "Author: System Crafters Community" and a hard-coded license on top for their personal stuff.

However, if there is interest for this to be a customization, I'm not opposed (just don't really see use for it, personally).

Regarding moving the skeleton (although I feel like this is already off the table), I agree with not moving it for now (however I'd keep it in mind for a `contributing` module, which I think we should move discussion to a separate issue for).

**Comment by jeffbowman** [comment]
While we have some `defcustom` variables around, adding more of them adds friction when someone is interested in moving away from Crafted Emacs (ie, when they outgrow it - assuming they do).  I'm not totally opposed to them, we should use them where they do provide value and make sense, but we will need something in the documentation about what it means to move away from them at some point.   This is a fairly low risk/friction point, so I'm not worried about it - maybe for a future release or whatever, but something I'm aware of at the moment. 

The more I think about new modules, those should pretty much always be developed in the context of the `crafted-emacs-home` location.  I'm not sure a Crafted Emacs module would be something someone developed outside of that path because they would (at least in theory) want to contribute it back to Crafted Emacs, so it would need to live there in the PR they would submit anyway.

**Comment by sthesing** [comment]
> While we have some `defcustom` variables around, adding more of them adds friction when someone is interested in moving away from Crafted Emacs (ie, when they outgrow it - assuming they do). 

I do agree with your general point and I think it's probably a good idea to think about when custom variable make sense for this project and when it is better to avoid them. I'll open a separate issue for that.

For this issue here (and also regarding the question of moving the skeleton), I thank you both for your arguments. It's probably not worth to change anything here. As @jvdydev pointed out : 

> I'm not sure that new modules are necessarily a frequent occurrence (to where one would want this customized)

Closing this. Again, thanks!
