### ISSUE TITLE
[craftedv2beta] Unused function `crafted-completion/minibuffer-backward-kill`

### ISSUE THREAD

**Issue by jvdydev** [SystemCrafters/crafted-emacs#356]
While looking through the code, I found that `crafted-completion/minibuffer-backward-kill` (`crafted-completion` module) is not actually mapped anywhere nor is it mentioned in the docs anywhere.

**Comment by jeffbowman** [comment]
Probably don't need it then.  Candidate for deletion.

**Comment by sthesing** [comment]
Addressed by #362
