### ISSUE TITLE
add move-text-internal and keybindings from the-efs-config(i think thats where i got it)

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/crafted-emacs#36]
this is what i had in my config that was based on emacs-from-scratch

```emacs-lisp
(defun move-text-internal (arg)
  (cond
   ((and mark-active transient-mark-mode)
    (if (> (point) (mark))
        (exchange-point-and-mark))
    (let ((column (current-column))
          (text (delete-and-extract-region (point) (mark))))
      (forward-line arg)
      (move-to-column column t)
      (set-mark (point))
      (insert text)
      (exchange-point-and-mark)
      (setq deactivate-mark nil)))
   (t
    (beginning-of-line)
    (when (or (> arg 0) (not (bobp)))
      (forward-line)
      (when (or (< arg 0) (not (eobp)))
        (transpose-lines arg))
      (forward-line -1)))))

(defun move-text-down (arg)
  "Move region (transient-mark-mode active) or current line
   arg lines down."
  (interactive "*p")
  (move-text-internal arg))

(defun move-text-up (arg)
  "Move region (transient-mark-mode active) or current line
   arg lines up."
  (interactive "*p")
  (move-text-internal (- arg)))

(global-set-key [\M-\S-down] 'move-text-down)
(global-set-key [\M-\S-up] 'move-text-up)
```

**Comment by jeffbowman** [comment]
An alternative is to use the `move-text` package.

**Comment by erikLundstedt** [comment]
> An alternative is to use the `move-text` package.

sure, but isnt part of the idea to use as much builtin functionality as possibe?

**Comment by ajxn** [comment]
Maybe use both solutions then?  Or ask David.

**Comment by erikLundstedt** [comment]
> Maybe use both solutions then?  Or ask David.

Yeah
Let the user decide

**Comment by theophilusx** [comment]
It is probably worth noting that Emacs has been moving some functionality which use to be in 'core' emacs into the GNU ELPA package repository.  So wanting to use 'core' Emacs functionality doesn't mean not using packages. It probably means we should prioritise packages from GNU ELPA (and maybe NONGNU ELPA) over other sources, such as MELPA or Github/Gitlab repositories?

**Comment by erikLundstedt** [comment]
closing (to cleanup) because its easy to implement yourself, install that package mentioned or copy from somewhere else


feel free to mention if anyone wants to do it
