### ISSUE TITLE
[v2] Corfu + Eglot have unsuitable performance for medium/large projects

### ISSUE THREAD

**Issue by mgmarlow** [SystemCrafters/crafted-emacs#369]
The combination of `corfu-auto-delay` of 0 and Eglot leads to bad performance when working in medium-to-large sized projects, as described in this Eglot discussion thread: https://github.com/joaotavora/eglot/discussions/993. This severely affects the editing experience in Emacs, causing keystrokes to take seconds before they register.

Here's the project statistics where I can repro the performance problem with crafted emacs, using the `crafted-completion` and `crafted-ide` modules:

```
 loc
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Typescript JSX        1823       235941        20848         3201       211892
 TypeScript             716        79512         7538         4170        67804
```

I've solved this in the past by increasing `corfu-auto-delay` as suggested by João in that discussion I linked above. Here's what it would look like for crafted-completion:

```diff
diff --git a/modules/crafted-completion-config.el b/modules/crafted-completion-config.el
index 360465a..b44406a 100644
--- a/modules/crafted-completion-config.el
+++ b/modules/crafted-completion-config.el
@@ -84,11 +84,11 @@
       (corfu-terminal-mode +1)))

   ;; Setup corfu for popup like completion
-  (customize-set-variable 'corfu-cycle t)                 ; Allows cycling through candidates
-  (customize-set-variable 'corfu-auto t)                  ; Enable auto completion
-  (customize-set-variable 'corfu-auto-prefix 2)           ; Complete with less prefix keys
-  (customize-set-variable 'corfu-auto-delay 0.0)          ; No delay for completion
-  (customize-set-variable 'corfu-echo-documentation 0.25) ; Echo docs for current completion option
+  (customize-set-variable 'corfu-cycle t)                ; Allows cycling through candidates
+  (customize-set-variable 'corfu-auto t)                 ; Enable auto completion
+  (customize-set-variable 'corfu-auto-prefix 2)          ; Complete with less prefix keys
+  (customize-set-variable 'corfu-auto-delay 0.25)        ; Short delay for Eglot compatibility
+  (customize-set-variable 'corfu-echo-documentation 0.5) ; Echo docs for current completion option

   (global-corfu-mode 1)
   (when (require 'corfu-popupinfo nil :noerror)
```

**Comment by jeffbowman** [comment]
I appreciate the statistics and research on this.  As we are providing a "general" solution, how do these changes affect small projects?  Basically, are there any usability issues for small projects or do you think the values you suggest would be appropriate for them as well?  Should we consider larger values like `0.33` for `corfu-auto-delay` to be safe?

**Comment by mgmarlow** [comment]
`0.33` might be a good call. I'm currently running with `0.25` and it works well for my purposes, but hard to say for larger projects. The effect of `corfu-auto-delay` will be the same for small projects, there's a slight delay before the completion popup shows up after typing. So as long as the delay is > 0 the experience should be fairly consistent across different project sizes.

I also just noticed this in the docs for `corfu-auto-delay`:

> It is *not recommended* to use a very small delay or even 0,
> since this will create high load for Emacs in particular if the
> completion backend in use is expensive.

In this case the completion backend is definitely expensive thanks to the LSP client, though I don't really know the details of how Eglot configures `completion-at-point`.

**Comment by jeffbowman** [comment]
Would it make more sense to leave the auto completion off as is the default with the package?  This would then put the configuration in the hands of the user rather than us providing an opinionated configuration.

**Comment by mgmarlow** [comment]
That's up for ya'll to decide, though I'd push to have it enabled by default. Depends on the audience but as someone coming from vscode it's one of the first things I searched for and enabled. Maybe the best middle-ground is to keep it enabled but keep the `corfu-auto-delay` value at the default value of `0.2`?
