### ISSUE TITLE
[v2]package-selected-packages "Combobulate" problem.

### ISSUE THREAD

**Issue by meleeis** [SystemCrafters/crafted-emacs#375]
### Operating System

Windows

### Emacs Version

29

### Emacs Configuration Details

- [ ] Native Compilation
- [ ] pGTK
- [x] alternative package manager (use-package, straight.el, ...)

### What happened?

when starting emacs, popup message output "1 packages are not available (the rest already installed)..."

### What should have happened?

simply bug.
"Combobulate is not on MELPA or any other package repository, yet"
(https://github.com/mickeynp/combobulate)

in "crafted-ide-packages.el"
please remove (add-to-list 'package-selected-packages 'combobulate).

**Comment by jvdydev** [comment]
Thank you for the bug report.

Am I understanding correctly that we remove only the package-selection for now (and re-add once `combobulate` is in MELPA or similar)?
This would keep the configuration for the people that want to manually install it, but get rid of the popup message.

**Comment by jeffbowman** [comment]
Yeah, we should do that.  Combobulate is available as source only, I jumped the gun adding it before it was available on a package repo (MELPA et.al).

**Comment by jeffbowman** [comment]
Fixed in  71b2905, closing.
