### ISSUE TITLE
Symbol's function definition is void: treesit-auto-add-to-auto-mode-alist

### ISSUE THREAD

**Issue by ingorichter** [SystemCrafters/crafted-emacs#388]
### Operating System

Mac

### Additional Operating System information

macOS 13.6

### Emacs Version

29

### Emacs Configuration Details

- [X] Native Compilation
- [ ] pGTK
- [ ] alternative package manager (use-package, straight.el, ...)

### What happened?

After pulling the latest from `craftedv2RC1`, I'm seeing this error

```
⛔ Warning (initialization): An error occurred while loading ‘/Users/i***r/emacs.d-crafted/init.el’:

Symbol's function definition is void: treesit-auto-add-to-auto-mode-alist

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Looks like the change to use `treesit-auto-add-to-auto-mode-alist` was introduced with this commit 91c1c9fd5afe88fbde256136c111d8a8556b0ff0

### What should have happened?

run through the initialization without any error (like before I pulled the latest from `craftedv2RC1`)

**Comment by mgmarlow** [comment]
That feature was just added to treesit-auto earlier today so I suspect you need to update your package to latest. `M-x list-packages`, mark treesit-auto `U` and install `x`. Sorry for the breaking change!

**Comment by jeffbowman** [comment]
To follow-up on what @mgmarlow says (just adding additional information here):

The update is in the `0.64` version of `treesit-auto` on `stable.melpa.org` or you can pull the development version from MELPA if you prefer.

**Comment by ingorichter** [comment]
Thank you. Manually updating solved the problem. Somehow I was under the impression that updates to installed packages will be installed automatically.
Closing this issue
