### ISSUE TITLE
Error loading crafted-ui-config.el

### ISSUE THREAD

**Issue by ingorichter** [SystemCrafters/crafted-emacs#423]
### Operating System

Mac

### Emacs Version

29

### Emacs Configuration Details

- [ ] Native Compilation
- [ ] pGTK
- [X] alternative package manager (use-package, straight.el, ...)

### What happened?

I'm loading the `crafted-ui-config.el` from my init.el and I get this error
```
Debugger entered--Lisp error: (void-function crafted-ui--update-line-numbers-display)
  (crafted-ui--update-line-numbers-display)
  (closure (t) (sym val) (set-default sym val) (crafted-ui--update-line-numbers-display))(crafted-ui-display-line-numbers nil)
  custom-initialize-reset(crafted-ui-display-line-numbers (funcall #'(closure (t) nil "" nil)))
  custom-declare-variable(crafted-ui-display-line-numbers (funcall #'(closure (t) nil "" nil)) "Whether line numbers should be enabled." :type boolean :group crafted-ui :set (closure (t) (sym val) (set-default sym val) (crafted-ui--update-line-numbers-display)))
  load-with-code-conversion("/Users/ingorichter/Documents/develop/crafted-emacs..." "/Users/ingorichter/Documents/develop/crafted-emacs..." nil t)
  require(crafted-ui-config)
  load-with-code-conversion("/Users/ingorichter/.emacs.d/init.el" "/Users/ingorichter/.emacs.d/init.el" t t)
  load("/Users/ingorichter/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x155ecd68801c79>) #f(compiled-function () #<bytecode -0x1f3c61addc0da035>) t)
  command-line()
  normal-top-level()
```

### What should have happened?

There shouldn't be an error.
The issue is, that the function `crafted-ui--update-line-numbers-display` is defined after `defcustom crafted-ui-display-line-numbers` is defined. Moving `defcustom` after the `crafted-ui--update-line-numbers-display` function resolves the problem

**Comment by sthesing** [comment]
Thanks for reporting this, @ingorichter. And for the accompanying diagnosis of the error.

Should be fixed by #424. Feel free to reopen if there are still problems.
