### ISSUE TITLE
Error while loading completion packages

### ISSUE THREAD

**Issue by melston** [SystemCrafters/crafted-emacs#426]
### Operating System

Windows

### Emacs Version

29

### Emacs Configuration Details

- [X] Native Compilation
- [ ] pGTK
- [ ] alternative package manager (use-package, straight.el, ...)

### What happened?

I am going through the "Getting Started" guide and got stuck on the second step.  When loading the completion packages I was getting the following error during startup:
```
File error: https://elpa.gnu.org/packages/embark-1.1.tar, No Data
```
I tried figuring out where this was coming from.  I saw, according to [this link](https://emacs.stackexchange.com/questions/60560/error-retrieving-https-elpa-gnu-org-packages-archive-contents-error-http-400) that it might be a TLS issue.  However, I tried the various diagnostics there and saw that TLS is a part of my distribution.  Also, using `eww` to load the archive pages gave no errors.

After looking at the various archive sites I noticed that the key suggested for the package-archives alist for the stable Melpa site is `melpa-stable` (rather than `stable`). I though "Why not give it a try" and now I don't see the error.  I don't know if changing the name to the recommended name avoided a conflict somewhere else but it now works. This may also be a Windows-only issue, but I wanted to report it.

For the record I changed:
```lisp
(add-to-list 'package-archives '("stable" . "https://stable.melpa.org/packages/") t)
```
to 
```lisp
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

### What should have happened?

No error on startup.

**Comment by jeffbowman** [comment]
Thanks for posting this issue.  

The name actually doesn't matter, as long as it is consistently used throughout your configuration.  In the `modules/crafted-early-init-config.el` file, you'll see the word "stable" wherever it refers to MELPA-stable. 

One thing that happens quite frequently on Windows (and I'm not sure how to fix it) are the errors that you experienced.  The solution is usually to restart emacs and allow it to continue to download packages.  In this case, restarting emacs is the "simplest" approach, but other approaches exist like running `(crafted-package-install-selected-packages)` or just iterating over the `package-selected-packages` list and installing everything that way.  For whatever reason, networking on Windows is not reliable and often drops or aborts in the middle of doing things which results in errors exactly like this. 

Note, you can get the same error if you run `M-x list-packages` then press 'U' to mark all the updates then `x` to install all the updates. You may need to do that process several times to get all the updates to actually install.  This only happens on MS Windows.  MacOS and Linux don't exhibit this problem (or rarely possibly - I've never encountered it on either system).

**Comment by melston** [comment]
Thanks for the response.  I did, as part of trying to figure things out, restart emacs several times and now it works. :)  I suppose that may have been what did it, though I did make a few changes, too.

Just part of the frustration of being stuck on Windows, I guess.

**Comment by melston** [comment]
It does seem to work now, though I am not sure if it was due to any changes I made or if it was just restarting emacs several times as @jeffbowman mentioned.

**Comment by jeffbowman** [comment]
> Thanks for the response. I did, as part of trying to figure things out, restart emacs several times and now it works. :) I suppose that may have been what did it, though I did make a few changes, too.
> 
> Just part of the frustration of being stuck on Windows, I guess.

Yeah, hard to know... I'm glad it works for you.  If you are stuck on MS Windows, you might also try WSL and run Emacs from there, not sure if running a Linux environment + Emacs on MS Windows would improve this situation or not, I don't use WSL at all and MS Windows rarely and only when a client demands it.
