### ISSUE TITLE
make doom-modeline optional

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/crafted-emacs#44]
im playing around with [powerline](https://github.com/milkypostman/powerline/tree/master) and similar packages and as far as i understand it is much closer to vanilla emacs modeline while allowing for lots of customization

im also thinking about playing around with [telephone-line](https://github.com/dbordak/telephone-line/tree/master) which seems to do ruffly the same

**Comment by daviwil** [comment]
@ajxn Honestly, I have a similar concern.  I think it would be nice if we could make our own nice looking, minimal mode line configuration that doesn't depend on an external package.  Mode line customization is a little harder to understand at first compared to general Emacs config, so it might be nice to have our own mode line here to serve as an example, as you suggested.

I made a recommendation in #45 to introduce a `rational-doom-modeline.el` instead, but I think what we really need first is our own `rational-modeline.el` that doesn't require an external package.

**Comment by erikLundstedt** [comment]
> @ajxn Honestly, I have a similar concern. I think it would be nice if we could make our own nice looking, minimal mode line configuration that doesn't depend on an external package. Mode line customization is a little harder to understand at first compared to general Emacs config, so it might be nice to have our own mode line here to serve as an example, as you suggested.
> 
> I made a recommendation in #45 to introduce a `rational-doom-modeline.el` instead, but I think what we really need first is our own `rational-modeline.el` that doesn't require an external package.

I know im late (by several months) to this, but the implementation I have(its now in my own config repo) allows the user to pick between the existing options(powerline and doom are the ones currently implemented) im thinking of this as more similar to the eglot vs LSP discussion,(powerline being lighter and more emacs-native) at least until we can make something fully custom, if at all.
my module currently allows the user to chose what modeline to use without having to write the config themselves if they dont want to, so merging it shouldn't be too hard

if someone here could help me get `crafted-modeline.el` up to standards that would be great as im not super comfortable in elisp and ive mainly done 1-person git projects where my code is mostly used by myself and where having unnecessary files isn't an issue. i`m also not too comfortable with github as im a gitlab user most of the time

**Comment by jeffbowman** [comment]
As requested on #246, Here is a repost of the comment from closing this issue.

> #44 has been around for quite a while, there were a couple attempts at closing it, but they never found their way into the system. I left it open hoping it would give someone else an opportunity to get involved. That never happened, so I have resolved that issue. Doom modeline is now optional and off by default. If you want it back on, customize the crafted-ui-use-doom-modeline to have a value of t.

Also, posting the commit message:

> This is a potentially "breaking" change for those who use
`doom-modeline`.  By default, it is no longer enabled when using this
module.  Instead, the user must enable it by setting the option
`crafted-ui-use-doom-modeline` to `t` in their `config.el` file.
