### ISSUE TITLE
Put modules in subdirectories for grouping etc

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/crafted-emacs#60]
This would require slightly modification to the init.el file

This means we can group sertain modules while keeping a good structure as talked about in pr #45

**Comment by theophilusx** [comment]
I think this is something we can consider once we have a sufficient number of modules to warrant it. At this point, it feels a little premature to be making the decision on how to group modules.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs V2
