### ISSUE TITLE
make relative linenumbers an easy option

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/crafted-emacs#99]
at the moment, in rational-ui, it forcefully sets linenumbers to either on or off, I cant find any whay to make it display relative linenumbers other than manually running mx (menu-bar-something-display-linunumbers-relative) every time I start emacs

i might have missed something but it looks like the setting is currently a boolean while the place it is used takes one of 3 values where 'relative is included

maybe add a relative option here:

```elisp
(defun rational-ui--enable-line-numbers-mode ()
  "Turn on line numbers mode.
Used as hook for modes which should display line numbers."
  (display-line-numbers-mode 1))

(defun rational-ui--disable-line-numbers-mode ()
  "Turn off line numbers mode.
Used as hook for modes which should not display line numebrs."
  (display-line-numbers-mode -1))
  ```

**Comment by erikLundstedt** [comment]
> In your `rational-config-file` you can add `(customize-set-variable 'display-line-numbers-type 'relative)` to use relative line numbers. For example, you might have something like this:
> 
> ```emacs-lisp
>     (require 'rational-ui)
> 
>     (with-eval-after-load "rational-ui"
>       (customize-set-variable 'rational-ui-display-line-numbers t)
>       (customize-set-variable 'display-line-numbers-type 'relative))
> ```
> 
> Does this help? If this addresses your issue, would you consider closing this issue? If not, please continue the discussion and we will help as best we can.

this seems to not have worked

might be an issue with the majormode not being in the "whitelist" but it shouldn`t be as it should be "derived" from `prog-mode`

**Comment by erikLundstedt** [comment]
uppdate


this seems to work but is ugly and might be the wrong way of doing it


```emacs-lisp
 (with-eval-after-load "rational-ui"
   (global-display-line-numbers-mode nil)
   (customize-set-variable 'display-line-numbers-type 'relative)
   (setq display-line-numbers-type 'relative)
   (customize-set-variable 'rational-ui-display-line-numbers t)
   (global-display-line-numbers-mode t)
   )
```

**Comment by erikLundstedt** [comment]
> update
> 
> this seems to work but is ugly and might be the wrong way of doing it
> 
> ```emacs-lisp
>  (with-eval-after-load "rational-ui"
>    (global-display-line-numbers-mode nil)
>    (customize-set-variable 'display-line-numbers-type 'relative)
>    (setq display-line-numbers-type 'relative)
>    (customize-set-variable 'rational-ui-display-line-numbers t)
>    (global-display-line-numbers-mode t)
>    )
> ```

```diff
- (setq display-line-numbers-type 'relative)
```
works

**Comment by jeffbowman** [comment]
Notice the order I call things in the example I provide. I customize the `rational-ui-display-line-numbers` variable **before** customizing the `display-line-numbers-type` value. In your examples, you invert that. Also, you use `global-display-line-numbers-mode` which I assume means you prefer to have line numbers displayed regardless of which major mode is being used. In this case, you don't need `rational-ui` at all (at least for the line-numbers configuration), these lines should do what you want:

``` emacs-lisp
    ;; don't need to use line number configuration in rational-ui if you want line numbers always displayed
    (customize-set-variable 'display-line-numbers-type 'relative)
    (global-display-line-numbers-mode)
```

And just to keep things close together, the original example: 

``` emacs-lisp
    (require 'rational-ui)

    (with-eval-after-load "rational-ui"
      ;; N.B. line numbers in rational-ui only turn them on for conf-mode and prog-mode (and derivatives)
      ;; line numbers are turned off in org-mode
      ;; order matters here.
      (customize-set-variable 'rational-ui-display-line-numbers t) ; must be set first as it configures modes for line numbers
      (customize-set-variable 'display-line-numbers-type 'relative)) ; configured after the line above to set the type to preference
```

Hope this helps!

**Comment by erikLundstedt** [comment]
>  ```emacs-lisp
      (with-eval-after-load "rational-ui"
      ;; N.B. line numbers in rational-ui only turn them on for conf-mode and prog-mode (and derivatives)
      ;; line numbers are turned off in org-mode
      ;; order matters here.
      (customize-set-variable 'rational-ui-display-line-numbers t) ; must be set first as it configures modes for line numbers
      (customize-set-variable 'display-line-numbers-type 'relative)) ; configured after the line above to set the type to preference
      ```
      i tried this and it didnt work

**Comment by jeffbowman** [comment]
Hmm... interesting. I tested it with only that in my `config.el` and it worked for me. Can you provide your configuration in a gist and I'll test more with what you have configured?

**Comment by erikLundstedt** [comment]
> Hmm... interesting. I tested it with only that in my `config.el` and it worked for me. Can you provide your configuration in a gist and I'll test more with what you have configured?

reversing the commands actually worked, interesting

my config is on my [gitlab](https://gitlab.com/Erik.Lundstedt/dotconfigfiles)
but it actually works now :-)

**Comment by erikLundstedt** [comment]
nevermind
